language: python
addons:
  apt:
    packages:
      - sshpass
python:
  - "2.7"
env:
  - ANSIBLE_VERSION=2.2.3.0
  - ANSIBLE_VERSION=2.3.0.0
install:
  - pip install -U wheel pip
  - pip install napalm
  - pip install ansible==$ANSIBLE_VERSION
  - pip install -e git+https://github.com/targuan/napalm-dummy.git#egg=napalm-dummy
script: 
  - cd tests && p=`which python` && sshpass -p test ansible-playbook playbook.yml -i hosts -e "ansible_python_interpreter=$p" -u test -k
  - cd tests && p=`which python` && test ansible-playbook playbook.yml -i hosts -e "ansible_python_interpreter=$p" -u test
cache: 
  pip:
  directories:
    - $HOME/.cache/pip
