language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install napalm
  - pip install ansible
# command to run tests
script: cd tests && p=`which python` && ansible-playbook playbook.yml -i hosts -e "ansible_python_interpreter=$p"
cache: pip
