language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install napalm
  - pip install ansible
# command to run tests
script: cd tests && ansible-playbook playbook.yml -i hosts
cache: pip
