language: python
addons:
  apt:
    packages:
      - sshpass
python:
  - "2.7"
env:
  - ANSIBLE_VERSION=2.3.1.0
  - ANSIBLE_VERSION=2.3.0.0
  - ANSIBLE_VERSION=2.2.3.0
  - ANSIBLE_VERSION=2.2.2.0
  - ANSIBLE_VERSION=2.2.1.0
  - ANSIBLE_VERSION=2.2.0.0
  - ANSIBLE_VERSION=2.1.6.0
  - ANSIBLE_VERSION=2.1.5.0
  - ANSIBLE_VERSION=2.1.4.0
  - ANSIBLE_VERSION=2.1.3.0
  - ANSIBLE_VERSION=2.1.2.0
  - ANSIBLE_VERSION=2.1.1.0
  - ANSIBLE_VERSION=2.1.0.0
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.0.0.2
  - ANSIBLE_VERSION=2.0.0.1
  - ANSIBLE_VERSION=1.9.6
  - ANSIBLE_VERSION=1.9.5
  - ANSIBLE_VERSION=1.9.4
install:
  - pip install -U wheel pip
  - pip install napalm
  - pip install ansible==$ANSIBLE_VERSION
  - pip install -e git+https://github.com/targuan/napalm-dummy.git#egg=napalm-dummy
script: 
  - cd tests
  - interpreter=`which python`
  - sshpass -p test ansible-playbook playbook.yml -i hosts -e "ansible_python_interpreter=$interpreter" -u test -k
  - ansible-playbook playbook.yml -i hosts -e "ansible_python_interpreter=$interpreter" -u test
  - ansible-playbook playbook.yml -i hosts -e "ansible_python_interpreter=$interpreter"
cache: 
  pip:
  directories:
    - $HOME/.cache/pip
