### requried
# this can be a company/brand or product namespace under which all content lives
namespace: "napalm_automation"
# the designation of this specific collection
name: "napalm"
# semantic versioning compliant version designation
version: 1.1
# a list of the collection's content authors: 'Full Name <email> (http://site) @nicks:irc/im/site#channel'
authors: "David Barroso, Kirk Byers, Mircea Ulinic"
# path to the license file for the collection.
readme: "README.md"



### optional but strongly advised
# short summary of the collection
description: "Network Automation and Programmability Abstraction Layer with Multivendor support"
# a valid SPDX license identifier https://spdx.org/licenses/
license_file: "LICENSE"
# list of dependencies, other collections this collection requires to be installed for it to be usable

### urls
# url of originating SCM repository
repository: "https://github.com/napalm-automation/napalm-ansible"
# url to online docs
documentation: "https://napalm.readthedocs.io/en/latest/tutorials/ansible-napalm.html"
# homepage of the collection/project
homepage: "https://github.com/napalm-automation/napalm-ansible"
# issue tracker url
issues: "https://github.com/napalm-automation/napalm-ansible/issues"
